apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: cv-data
          persistentVolumeClaim:
            claimName: cv-storage-claim
      containers:
        - name: cv-adapter-be
          image: cv-adapter-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cv-data
              mountPath: /data