apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: cv-adapter-fe
          image: cv-adapter-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always
      